local M = {
	hero = {
		health = 10,
		attack = 3,
		attack_speed = 1,
		speed = 50,
		orders = hash("explore")
	},
	spider = {
		type = hash("spider"),
		health = 3,
		attack = 2,
		attack_speed = 0.5,
		callCost = 10,
		empowerCost = 30,
		speed = 35,
		bounty = 1
	},
	spider_boss = {
		type = hash("spider_boss"),
		health = 75,
		attack = 6,
		attack_speed = 1.2,
		speed = 10,
		bounty = 40,
		orders = hash("build"),
		build_time = 3,
		spawn_time = 2,
		spawn_limit = 60
	},
	goblin = {
		type = hash("goblin"),
		health = 8,
		attack = 3,
		attack_speed = 0.8,
		callCost = 15,
		empowerCost = 35,
		speed = 30,
		bounty = 3,
	},
	goblin_worker = {
		type = hash("goblin_worker"),
		health = 8,
		attack = 1,
		attack_speed = 1.5,
		speed = 28,
		bounty = 0,
		orders = hash("mine"),
		workTime = 3
	},
	goblin_boss = {
		type = hash("goblin_boss"),
		health = 50,
		attack = 15,
		attack_speed = 0.9,
		speed = 26,
		bounty = 50,
		orders = hash("build"),
		build_time = 5,
		spawn_time = 4,
		spawn_limit = 75,
		spawn_limit_worker = 10
	},
	drake = {
		type = hash("drake"),
		health = 60,
		attack = 30,
		attack_speed = 1.4,
		callCost = 100,
		empowerCost = 200,
		speed = 45,
		bounty = 100,
	},
	drake_boss = {
		type = hash("drake_boss"),
		health = 100,
		attack = 55,
		attack_speed = 1.2,
		speed = 47,
		bounty = 250,
	},
	orc = {
		type = hash("orc"),
		health = 75,
		attack = 20,
		attack_speed = 1.5,
		callCost = 50,
		empowerCost = 500,
		speed = 15,
		bounty = 80,
	},
	orc_boss = {
		type = hash("orc_boss"),
		health = 150,
		attack = 30,
		attack_speed = 0.5,
		speed = 13,
		bounty = 500,
		orders = hash("build"),
		build_time = 8,
		spawn_time = 6,
		spawn_limit = 30,
		spawn_limit_worker = 7
	},
	orc_cultist = {
		type = hash("orc_cultist"),
		health = 60,
		attack = 25,
		attack_speed = 0.8,
		speed = 13,
		bounty = 300,
		orders = hash("worship"),
		workTime = 5,
	},
}

return M