go.property("type", hash("spider"))

function init(self)
	if self.type == hash("spider_boss") then
		sprite.play_flipbook("#sprite", "spider")
	elseif self.type == hash("goblin_boss") then
		sprite.play_flipbook("#sprite", "goblin")
	end
end

function die(self)
	go.delete(go.get_id(), true)
end

function on_message(self, message_id, message, sender)
	if message_id == hash("die") then
		go.animate("#sprite", "tint.w", go.PLAYBACK_ONCE_FORWARD, 0, go.EASING_LINEAR, 2, 0, die)
	end
end